// Copyright 2018-2020 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

package server

import (
	"strings"

	"github.com/gopcua/opcua/ua"
	"github.com/gopcua/opcua/uapolicy"
	"github.com/gopcua/opcua/uasc"
)

// AuthenticationRequest describes a client's attempt to activate a session.
// It is passed to the Authenticator configured with the Authenticator()
// option.
type AuthenticationRequest struct {
	// TokenType is the type of the user identity token presented by the
	// client. A missing or null identity token maps to
	// ua.UserTokenTypeAnonymous.
	TokenType ua.UserTokenType

	// PolicyID is the policy ID of the user token policy selected by the
	// client.
	PolicyID string

	// UserName is set when TokenType is ua.UserTokenTypeUserName.
	UserName string

	// Password is the decrypted password when TokenType is
	// ua.UserTokenTypeUserName.
	Password []byte

	// Certificate is the DER encoded certificate of the user identity
	// token when TokenType is ua.UserTokenTypeCertificate.
	//
	// Note: the user token signature is NOT verified by the server yet.
	// Authenticators must not trust this certificate as proof of
	// possession of the private key.
	Certificate []byte

	// ClientCertificate is the DER encoded application instance
	// certificate provided in CreateSession. Empty for unsecured channels
	// when the client did not provide one.
	ClientCertificate []byte

	// ClientDescription as provided in CreateSession.
	ClientDescription *ua.ApplicationDescription

	// EndpointURL the session was created against.
	EndpointURL string

	// RemoteAddr is the network address of the client.
	RemoteAddr string
}

// Authenticator decides whether a session activation is allowed.
//
// Returning nil accepts the ActivateSession request. Return a ua.StatusCode
// error (e.g. ua.StatusBadUserAccessDenied, ua.StatusBadIdentityTokenRejected
// or ua.StatusBadCertificateUntrusted) to reject the request with that code;
// any other error is mapped to ua.StatusBadUserAccessDenied.
//
// When an Authenticator is configured, all services other than discovery and
// session management require an activated session. Service requests on
// non-activated sessions are rejected with ua.StatusBadSessionNotActivated.
type Authenticator func(req *AuthenticationRequest) error

// Authenticator sets the authenticator the server uses during session
// activation. Without one, all session activations are accepted (upstream
// gopcua behavior).
func WithAuthenticator(a Authenticator) Option {
	return func(s *serverConfig) {
		s.authenticator = a
	}
}

// userTokenSecurityPolicyURI maps the policy ID of a user token policy
// generated by initEndpoints (e.g. "username_basic256sha256") back to the
// security policy URI used to encrypt the token secret. It falls back to the
// secure channel's policy when the ID has no known suffix.
func userTokenSecurityPolicyURI(policyID string) string {
	i := strings.Index(policyID, "_")
	if i < 0 || i+1 >= len(policyID) {
		return ""
	}

	suffix := policyID[i+1:]

	if strings.EqualFold(suffix, "none") {
		return ua.SecurityPolicyURINone
	}

	for _, uri := range uapolicy.SupportedPolicies() {
		short := strings.TrimPrefix(uri, ua.SecurityPolicyURIPrefix)
		if strings.EqualFold(short, suffix) {
			return uri
		}
	}

	return ""
}

// buildAuthenticationRequest parses the user identity token of an
// ActivateSessionRequest, decrypting the password if necessary.
func buildAuthenticationRequest(sc *uasc.SecureChannel, sess *session, req *ua.ActivateSessionRequest) (*AuthenticationRequest, error) {
	areq := &AuthenticationRequest{
		TokenType:         ua.UserTokenTypeAnonymous,
		ClientCertificate: sess.remoteCertificate,
		ClientDescription: sess.clientDescription,
		EndpointURL:       sess.endpointURL,
		RemoteAddr:        sess.remoteAddr,
	}

	if req.UserIdentityToken == nil || req.UserIdentityToken.Value == nil {
		return areq, nil
	}

	switch tok := req.UserIdentityToken.Value.(type) {
	case *ua.AnonymousIdentityToken:
		areq.PolicyID = tok.PolicyID

	case *ua.UserNameIdentityToken:
		areq.TokenType = ua.UserTokenTypeUserName
		areq.PolicyID = tok.PolicyID
		areq.UserName = tok.UserName

		if tok.EncryptionAlgorithm == "" {
			// An unencrypted password is only acceptable when the effective
			// user-token security policy is explicitly None. Otherwise the
			// password MUST be encrypted (OPC-UA Part 4); trusting cleartext
			// here would let a client downgrade and submit a password that
			// should have required encryption. Default-deny: an unknown /
			// missing PolicyID does not resolve to None and is rejected.
			if userTokenSecurityPolicyURI(tok.PolicyID) != ua.SecurityPolicyURINone {
				return nil, ua.StatusBadIdentityTokenInvalid
			}
			areq.Password = tok.Password
			return areq, nil
		}

		policyURI := userTokenSecurityPolicyURI(tok.PolicyID)
		pass, err := sc.DecryptUserPassword(policyURI, tok.Password, sess.serverNonce)
		if err != nil {
			return nil, ua.StatusBadIdentityTokenInvalid
		}
		areq.Password = pass

	case *ua.X509IdentityToken:
		areq.TokenType = ua.UserTokenTypeCertificate
		areq.PolicyID = tok.PolicyID
		areq.Certificate = tok.CertificateData

	case *ua.IssuedIdentityToken:
		areq.TokenType = ua.UserTokenTypeIssuedToken
		areq.PolicyID = tok.PolicyID

	default:
		return nil, ua.StatusBadIdentityTokenInvalid
	}

	return areq, nil
}
